#!/bin/bash -l

#PBS -l walltime=24:00:00
#PBS -l nodes=5:ppn=1
#PBS -l mem=10gb
#PBS -m bae
#PBS -o $HOME/tuning-tabu/irace-tabu.stdout 
#PBS -e $HOME/tuning-tabu/irace-tabu.stderr 
#PBS -N tabu_pcol

module load graph-tool/2.2.42-foss-2015a-Python-2.7.9
module load R/3.1.1-intel-2014b

MPIRUN=mpirun

cd $HOME/tuning-tabu

$MPIRUN -outfile-pattern $HOME/tuning-tabu/mpi.out -errfile-pattern $HOME/tuning-tabu/mpi.err -np 1 $IRACE_HOME/bin/irace --exec-dir=$HOME/tuning-tabu/arena --mpi 1 --parallel 4
