#!/bin/bash -l

#PBS -l walltime=24:00:00
#PBS -l nodes=4:ppn=8
#PBS -l mem=60gb
#PBS -m base
#PBS -o $EXECDIR/irace-$$.stdout 
#PBS -e $EXECDIR/irace-$$.stderr 
#PBS -cwd

module load graph-tool/2.2.42-foss-2015a-Python-2.7.9
module load R/3.1.1-intel-2014b

MPIRUN=mpirun

cd $HOME/tuning

$MPIRUN -np 1 -output-filename $HOME/mpi.out $BINDIR/irace --exec-dir=$HOME/tuning --parallel 10 --mpi 1 
