#!/bin/bash -l

#PBS -l walltime=24:00:00
#PBS -l nodes=4:ppn=8
#PBS -l mem=60gb
#PBS -m bae
#PBS -o $EXECDIR/irace-partial.stdout 
#PBS -e $EXECDIR/irace-partial.stderr 

module load graph-tool/2.2.42-foss-2015a-Python-2.7.9
module load R/3.1.1-intel-2014b

MPIRUN=mpirun

cd $HOME/tuning

$MPIRUN -outfile-pattern $HOME/mpi.out -errfile-pattern $HOME/mpi.err -np 1 $IRACE_HOME/bin/irace --exec-dir=$HOME/tuning/partial-arena --mpi 1 --parallel 20
