#!/bin/bash -l

#PBS -l walltime=24:00:00
#PBS -l nodes=11
#PBS -l mem=60gb

set -e
set -o pipefail

MPIRUN=/opt/openmpi/bin/mpirun
module load graph-tool/2.2.42-foss-2015a-Python-2.7.9
module load R/3.1.1-intel-2014b

if [ $# == 0 ]; then
    echo "Usage: ./tune-main-cluster-mpi <BINDIR> <EXECDIR> --parallel <NB_SLAVES> additional_args_to_irace"
    exit 1
fi

BINDIR=$1
EXECDIR=$2
shift 2
NB_SLAVES=0

PARAMS=
while [ $# -gt 0 ]; do
    case "$1" in
        --parallel) shift; NB_SLAVES="$1"; shift;;
        *) PARAMS="$PARAMS $1"; shift;;# terminate case
  esac
done

if [ $NB_SLAVES -lt 2 ]; then
    echo "$0: error: --parallel must be larger than 1"
    exit 1
fi

export OMPI_MCA_plm_rsh_disable_qrsh=1

$MPIRUN -np 1 $BINDIR/irace --exec-dir=$EXECDIR --parallel $NB_SLAVES --mpi 1 $PARAMS
