#!/bin/bash -l

#PBS -l walltime=24:00:00
#PBS -l nodes=21
#PBS -l mem=60gb
#PBS -m bae
#PBS -o $HOME/irace-react_partial.stdout 
#PBS -e $HOME/irace-react_partial.stderr 

module load graph-tool/2.2.42-foss-2015a-Python-2.7.9
module load R/3.1.1-intel-2014b

MPIRUN=mpirun

cd $HOME/tuning-react-partial

$MPIRUN -outfile-pattern $HOME/tuning-react-partial/mpi.out -errfile-pattern $HOME/tuning-react-partial/mpi.err -np 1 $IRACE_HOME/bin/irace --exec-dir=$HOME/tuning-react-partial/arena --mpi 1 --parallel 4
